import type { CATItem } from "./types";

export const ITEM_BANK: CATItem[] = [
  // ─── Ear Training: Degree Recognition ──────────────────
  {
    id: "cat-et-1",
    dimension: "degree_1",
    group: "degree_recognition",
    difficulty: 1,
    item_type: "aural",
    prompt: "Listen to the note over the drone. Is it tonic (Do)?",
    options: [
      { id: "yes", label: "Yes — Do (1)" },
      { id: "no", label: "No — different degree" },
    ],
    correct_answer: "yes",
    audio_degrees: [1],
    drone_key: "C",
  },
  {
    id: "cat-et-2",
    dimension: "degree_1",
    group: "degree_recognition",
    difficulty: 3,
    item_type: "multiple_choice",
    prompt: "Which degree feels like 'home' — the point of rest?",
    options: [
      { id: "a", label: "Do (1)" },
      { id: "b", label: "Sol (5)" },
      { id: "c", label: "Re (2)" },
      { id: "d", label: "La (6)" },
    ],
    correct_answer: "a",
  },
  {
    id: "cat-et-3",
    dimension: "degree_5",
    group: "degree_recognition",
    difficulty: 2,
    item_type: "aural",
    prompt: "Listen to the note. Which degree is it?",
    options: [
      { id: "a", label: "Do (1)" },
      { id: "b", label: "Sol (5)" },
      { id: "c", label: "Mi (3)" },
    ],
    correct_answer: "b",
    audio_degrees: [5],
    drone_key: "C",
  },
  {
    id: "cat-et-4",
    dimension: "degree_3",
    group: "degree_recognition",
    difficulty: 3,
    item_type: "aural",
    prompt: "Listen. Which triad member is this?",
    options: [
      { id: "a", label: "Do (1)" },
      { id: "b", label: "Mi (3)" },
      { id: "c", label: "Sol (5)" },
    ],
    correct_answer: "b",
    audio_degrees: [3],
    drone_key: "C",
  },
  {
    id: "cat-et-5",
    dimension: "degree_2",
    group: "degree_recognition",
    difficulty: 4,
    item_type: "aural",
    prompt: "Listen to the note. Which degree?",
    options: [
      { id: "a", label: "Do (1)" },
      { id: "b", label: "Re (2)" },
      { id: "c", label: "Mi (3)" },
      { id: "d", label: "Fa (4)" },
    ],
    correct_answer: "b",
    audio_degrees: [2],
    drone_key: "C",
  },
  {
    id: "cat-et-6",
    dimension: "degree_1",
    group: "degree_recognition",
    difficulty: 5,
    item_type: "multiple_choice",
    prompt: "Which degree has the strongest pull toward tonic?",
    options: [
      { id: "a", label: "Sol (5)" },
      { id: "b", label: "Ti (7)" },
      { id: "c", label: "Re (2)" },
      { id: "d", label: "Fa (4)" },
    ],
    correct_answer: "b",
  },

  // ─── Ear Training: Intervals ──────────────────────────
  {
    id: "cat-ei-1",
    dimension: "interval_id",
    group: "ear_training",
    difficulty: 2,
    item_type: "aural",
    prompt: "Listen to the two notes. What is the interval?",
    options: [
      { id: "a", label: "Minor 2nd" },
      { id: "b", label: "Major 2nd" },
      { id: "c", label: "Perfect 5th" },
    ],
    correct_answer: "c",
    audio_degrees: [1, 5],
    drone_key: "C",
  },
  {
    id: "cat-ei-2",
    dimension: "interval_id",
    group: "ear_training",
    difficulty: 4,
    item_type: "aural",
    prompt: "Identify this interval.",
    options: [
      { id: "a", label: "Major 3rd" },
      { id: "b", label: "Perfect 4th" },
      { id: "c", label: "Minor 3rd" },
      { id: "d", label: "Major 2nd" },
    ],
    correct_answer: "b",
    audio_degrees: [1, 4],
    drone_key: "C",
  },

  // ─── Ear Training: Chord Quality ──────────────────────
  {
    id: "cat-ec-1",
    dimension: "chord_quality",
    group: "ear_training",
    difficulty: 2,
    item_type: "multiple_choice",
    prompt: "A major chord sounds...",
    options: [
      { id: "a", label: "Bright and happy" },
      { id: "b", label: "Dark and sad" },
      { id: "c", label: "Tense and unresolved" },
    ],
    correct_answer: "a",
  },
  {
    id: "cat-ec-2",
    dimension: "chord_quality",
    group: "ear_training",
    difficulty: 4,
    item_type: "multiple_choice",
    prompt: "What makes a minor chord different from a major chord?",
    options: [
      { id: "a", label: "The root is lower" },
      { id: "b", label: "The third is lowered by a half step" },
      { id: "c", label: "The fifth is raised" },
      { id: "d", label: "It has four notes" },
    ],
    correct_answer: "b",
  },

  // ─── Theory: Key Signatures ───────────────────────────
  {
    id: "cat-th-1",
    dimension: "key_signatures",
    group: "theory",
    difficulty: 1,
    item_type: "multiple_choice",
    prompt: "How many sharps or flats does C Major have?",
    options: [
      { id: "a", label: "None" },
      { id: "b", label: "One sharp" },
      { id: "c", label: "One flat" },
    ],
    correct_answer: "a",
  },
  {
    id: "cat-th-2",
    dimension: "key_signatures",
    group: "theory",
    difficulty: 3,
    item_type: "multiple_choice",
    prompt: "How many sharps are in the key of A Major?",
    options: [
      { id: "a", label: "1" },
      { id: "b", label: "2" },
      { id: "c", label: "3" },
      { id: "d", label: "4" },
    ],
    correct_answer: "c",
  },
  {
    id: "cat-th-3",
    dimension: "key_signatures",
    group: "theory",
    difficulty: 5,
    item_type: "multiple_choice",
    prompt: "Which key has 5 flats?",
    options: [
      { id: "a", label: "Db Major" },
      { id: "b", label: "Ab Major" },
      { id: "c", label: "Gb Major" },
      { id: "d", label: "Cb Major" },
    ],
    correct_answer: "a",
  },

  // ─── Theory: Scales ───────────────────────────────────
  {
    id: "cat-ts-1",
    dimension: "scales",
    group: "theory",
    difficulty: 2,
    item_type: "multiple_choice",
    prompt: "A major scale has how many notes?",
    options: [
      { id: "a", label: "5" },
      { id: "b", label: "7" },
      { id: "c", label: "8" },
      { id: "d", label: "12" },
    ],
    correct_answer: "b",
  },
  {
    id: "cat-ts-2",
    dimension: "scales",
    group: "theory",
    difficulty: 4,
    item_type: "multiple_choice",
    prompt: "Major scale with a flat 7th is which mode?",
    options: [
      { id: "a", label: "Dorian" },
      { id: "b", label: "Lydian" },
      { id: "c", label: "Mixolydian" },
      { id: "d", label: "Phrygian" },
    ],
    correct_answer: "c",
  },

  // ─── Theory: Roman Numerals ───────────────────────────
  {
    id: "cat-tr-1",
    dimension: "roman_numerals",
    group: "theory",
    difficulty: 2,
    item_type: "multiple_choice",
    prompt: "In Roman numeral analysis, 'I' represents which chord?",
    options: [
      { id: "a", label: "The tonic chord" },
      { id: "b", label: "The dominant chord" },
      { id: "c", label: "The subdominant chord" },
    ],
    correct_answer: "a",
  },
  {
    id: "cat-tr-2",
    dimension: "roman_numerals",
    group: "theory",
    difficulty: 4,
    item_type: "multiple_choice",
    prompt: "What does a lowercase Roman numeral (e.g., 'ii') indicate?",
    options: [
      { id: "a", label: "An inverted chord" },
      { id: "b", label: "A minor chord" },
      { id: "c", label: "A diminished chord" },
      { id: "d", label: "A secondary dominant" },
    ],
    correct_answer: "b",
  },

  // ─── Rhythm: Rhythm Accuracy ──────────────────────────
  {
    id: "cat-rh-1",
    dimension: "rhythm_accuracy",
    group: "rhythm",
    difficulty: 1,
    item_type: "multiple_choice",
    prompt: "How many beats does a quarter note last in 4/4 time?",
    options: [
      { id: "a", label: "Half a beat" },
      { id: "b", label: "One beat" },
      { id: "c", label: "Two beats" },
    ],
    correct_answer: "b",
  },
  {
    id: "cat-rh-2",
    dimension: "rhythm_accuracy",
    group: "rhythm",
    difficulty: 3,
    item_type: "rhythm_tap",
    prompt: "Tap along with this rhythm pattern.",
    correct_answer: "tap_accuracy_80",
    rhythm_config: {
      tempo: 80,
      time_signature: [4, 4],
      pattern: [
        { beat: 1, duration: 1 },
        { beat: 2, duration: 1 },
        { beat: 3, duration: 0.5 },
        { beat: 3.5, duration: 0.5 },
        { beat: 4, duration: 1 },
      ],
    },
  },
  {
    id: "cat-rh-3",
    dimension: "rhythm_accuracy",
    group: "rhythm",
    difficulty: 5,
    item_type: "multiple_choice",
    prompt:
      "A dotted quarter note followed by an eighth note spans how many beats?",
    options: [
      { id: "a", label: "1 beat" },
      { id: "b", label: "1.5 beats" },
      { id: "c", label: "2 beats" },
      { id: "d", label: "3 beats" },
    ],
    correct_answer: "c",
  },

  // ─── Rhythm: Meter ID ─────────────────────────────────
  {
    id: "cat-rm-1",
    dimension: "meter_id",
    group: "rhythm",
    difficulty: 2,
    item_type: "multiple_choice",
    prompt: "What does the top number in a time signature tell you?",
    options: [
      { id: "a", label: "How many beats per measure" },
      { id: "b", label: "The tempo" },
      { id: "c", label: "Which note gets the beat" },
    ],
    correct_answer: "a",
  },
  {
    id: "cat-rm-2",
    dimension: "meter_id",
    group: "rhythm",
    difficulty: 4,
    item_type: "multiple_choice",
    prompt: "3/4 time groups beats into sets of...",
    options: [
      { id: "a", label: "2 (strong-weak)" },
      { id: "b", label: "3 (strong-weak-weak)" },
      { id: "c", label: "4 (strong-weak-medium-weak)" },
    ],
    correct_answer: "b",
  },

  // ─── Sight-Reading: Note Reading ──────────────────────
  {
    id: "cat-sr-1",
    dimension: "note_reading",
    group: "sight_reading",
    difficulty: 1,
    item_type: "multiple_choice",
    prompt: "The treble clef space notes from bottom to top spell...",
    options: [
      { id: "a", label: "FACE" },
      { id: "b", label: "BEAD" },
      { id: "c", label: "CAGE" },
    ],
    correct_answer: "a",
  },
  {
    id: "cat-sr-2",
    dimension: "note_reading",
    group: "sight_reading",
    difficulty: 3,
    item_type: "multiple_choice",
    prompt: "The bottom line of the treble clef is which note?",
    options: [
      { id: "a", label: "C" },
      { id: "b", label: "D" },
      { id: "c", label: "E" },
      { id: "d", label: "F" },
    ],
    correct_answer: "c",
  },
  {
    id: "cat-sr-3",
    dimension: "note_reading",
    group: "sight_reading",
    difficulty: 4,
    item_type: "multiple_choice",
    prompt: "The bass clef line notes from bottom to top are...",
    options: [
      { id: "a", label: "E, G, B, D, F" },
      { id: "b", label: "G, B, D, F, A" },
      { id: "c", label: "A, C, E, G, B" },
    ],
    correct_answer: "b",
  },
  {
    id: "cat-sr-4",
    dimension: "note_reading",
    group: "sight_reading",
    difficulty: 5,
    item_type: "multiple_choice",
    prompt: "Middle C appears on which ledger line?",
    options: [
      { id: "a", label: "Below the treble clef staff" },
      { id: "b", label: "Above the treble clef staff" },
      { id: "c", label: "On the third line of the treble clef" },
      { id: "d", label: "On the first line of the bass clef" },
    ],
    correct_answer: "a",
  },
];
